apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-vault-secret
  namespace: ultimatenew
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: hello-vault-secret
  data:
    - secretKey: message
      remoteRef:
        key: hello
        property: message
